### ISSUE TITLE
Not possible to modify the response body

### ISSUE THREAD

**Issue by Slowacki** [RoadTrain/ReverseProxyMiddleware#1]
The reverse proxy middleware on its own works pretty well, however, I'm in a situation where I need to modify the body of the response.

The usual way of approaching it is swapping the Stream object in the Response for a MemoryStream, which can be rewound, reread and rewritten (https://stackoverflow.com/questions/43403941/how-to-read-asp-net-core-response-body/43404745). However, that seems to be not possible when using the reverse proxy, as we don't have the access to the response until after it already has the body written to a Stream.

I feel like this should be part of the Middleware class, to enable consumers of this project to freely modify their response body in the ResponseModifier.

I've created a fork of the project, did the stream swapping there and currently use that version of the project as a workaround. If you're interested I could create a PR with that change, then I could just use the NuGet package instead again :)

**Comment by RoadTrain** [comment]
Hello!

Yeah, I don't mind adding your code to the package if it works.
Feel free to create a PR :+1:
